### ISSUE TITLE
Feature request: asynchronous streaming of batches of CommandList responses

### ISSUE THREAD

**Issue by rw** [Bunogi/darkredis#9]
Pipelined command results would be more performant and ergonomic if they were streamed back to the user, instead of batched and allocated.

**Comment by Bunogi** [comment]
I did some work on this. I pushed the comparison to the `commandlist_stream` branch. It appears to be slightly slower when just `collect()`ing the results. 

This is a good chance to wrap *every* response in a `Result` as it's a breaking change anyway. However, we should probably keep the old interface around(with the return type tweak), since it can be faster in certain situations where you don't care for processing each element in a stream.

**Comment by rw** [comment]
Personally, I'd rather make breaking changes now to make it more performant and more correct -- forcing the API to be stable too early can be a big problem.

**Comment by Bunogi** [comment]
This has now landed in 6634fce. I left only the streaming version.
